#!/bin/bash
# 验证 preToolUse / postToolUse STDOUT 是否注入 LLM 上下文
# 方法：配置 hook 输出特定 marker，然后观察 agent 是否能引用该 marker

echo "=== Hook STDOUT 注入行为分析 ==="
echo ""
echo "根据 Kiro 文档的精确描述："
echo ""
echo "1. agentSpawn (exit 0):"
echo "   'STDOUT is added to agent's context'"
echo "   → ✅ 明确注入上下文"
echo ""
echo "2. userPromptSubmit (exit 0):"
echo "   'STDOUT is added to agent's context'"
echo "   → ✅ 明确注入上下文"
echo ""
echo "3. preToolUse (exit 0):"
echo "   'Allow tool execution.'"
echo "   → ❓ 没有提到 STDOUT 的去向"
echo "   通用描述: 'STDOUT is captured but not shown to user'"
echo "   → 被捕获但不展示给用户。'captured' ≠ 'added to context'"
echo ""
echo "4. postToolUse (exit 0):"
echo "   'Hook succeeded.'"
echo "   → ❓ 没有提到 STDOUT 的去向"
echo "   同样适用通用描述: 'captured but not shown to user'"
echo ""
echo "5. stop (exit 0):"
echo "   'Hook succeeded.'"
echo "   → ❓ 同上"
echo ""
echo "=== 结论 ==="
echo ""
echo "文档中只有 agentSpawn 和 userPromptSubmit 明确说 STDOUT 注入上下文。"
echo "preToolUse/postToolUse/stop 的 STDOUT 被'捕获'但文档未确认注入 LLM 上下文。"
echo ""
echo "需要实际运行验证。测试方法："
echo "1. 配置 hook-stdout-test agent"
echo "2. 用 kiro-cli chat --agent hook-stdout-test 启动"
echo "3. 让 agent 执行一个 shell 命令"
echo "4. 观察 agent 是否能引用 MAGIC_MARKER"
